### ISSUE TITLE
SVG fails

### ISSUE THREAD

**Issue by tnrn9b** [marwanhamdan2/openhtmltopdf-npm#1]
the openhtmltopdf has support for svg images but the node version isn't working. any tips?

**Comment by marwanhamdan2** [comment]
could you please provide me an html sample contains svg, with the expected pdf output.

**Comment by tnrn9b** [comment]
[SVG Data.zip](https://github.com/marwanhamdan2/openhtmltopdf-npm/files/1066611/SVG.Data.zip)

**Comment by marwanhamdan2** [comment]
Thanks, honestly all credits are to the author of https://github.com/danfickle/openhtmltopdf.
This module just embed the library in a jar file and make it easy to use with node.
I will fix this issue very soon.

**Comment by marwanhamdan2** [comment]
Issue is fixed at version (1.0.8). Note: use the following reference to make sure you are using the SVG components in the right way library detects in order to avoid odd rendering issues.
https://openhtmltopdf.com/template-guide.pdf

Please review and let me know whether  it works for you.
You are always welcome to review and report issues.

**Comment by tnrn9b** [comment]
It works. Here's an example.
[SVG Example.zip](https://github.com/marwanhamdan2/openhtmltopdf-npm/files/1067678/SVG.Example.zip)
